### ISSUE TITLE
无法定位程序输入点

### ISSUE THREAD

**Issue by Pi-ka7** [doimet/AuxTools#12]
![图片](https://user-images.githubusercontent.com/57211343/198911111-2d76e1df-df5b-4167-bea0-203d3dc12eef.png)

**Comment by Pi-ka7** [comment]
![图片](https://user-images.githubusercontent.com/57211343/198911404-17638132-b822-48ec-8c21-d17290bb3758.png)
缺少东西，是不是在打包得时候得打包进去呢，还是只需要单独下载下

**Comment by doimet** [comment]
系统版本发下，有时间我测试看看
