### ISSUE TITLE
123

### ISSUE THREAD

**Issue by sasosos** [doimet/AuxTools#19]
能不能搞个漏洞利用模块的一键全选功能，或者信息搜集之后的数据可以下载？

**Comment by doimet** [comment]
1. 漏洞利用的全选功能有一个bug，全选只能选中一部分，有时间会解决这个问题
2. 信息搜集后的数据下载，选中想要导出的数据->鼠标右键点击->弹出菜单->导出数据，即可导出搜集的结果
