### ISSUE TITLE
打开是白屏

### ISSUE THREAD

**Issue by moondeft** [doimet/AuxTools#2]
![image](https://user-images.githubusercontent.com/86820315/169249463-956de3eb-5ca5-40e4-a58e-5fc5fbc3c1ad.png)

**Comment by doimet** [comment]
在虚拟机里运行程序，界面显示空白，解决方法如下:
1. 如果是VMware，请打开菜单编辑->首选项->显示->勾选远程虚拟机的硬件加速选项；如果打开还是白屏, 编辑虚拟机设置->显示器->3D图形->取消勾选3D加速图形
2. 如果是VirtualBox，请打开设置->显示->显卡->勾选3D加速选项
