### ISSUE TITLE
漏洞功能一直验证失败（但确实存在漏洞）

### ISSUE THREAD

**Issue by csxxy** [doimet/AuxTools#23]
以DC-1和DC-3靶机为例，fscan能检测到漏洞
![图片](https://github.com/doimet/AuxTools/assets/104177738/50a228ac-c416-4946-a8a3-472dbcb2a3fb)
![图片](https://github.com/doimet/AuxTools/assets/104177738/720ffeac-c4cb-4265-bb41-50e08ae91d1b)

**Comment by doimet** [comment]
5.X版本会重做这个模块，到时会修复这个问题
