### ISSUE TITLE
杀软识别模块识别结果显示异常

### ISSUE THREAD

**Issue by wx1029** [doimet/AuxTools#3]
杀软识别模块识别结果显示异常
![Uploading 1663301729460.png…]()

**Comment by wx1029** [comment]
![1663301729460](https://user-images.githubusercontent.com/52392598/190555557-14f0c0cb-7535-4326-90cb-2cb6304e13bb.png)

**Comment by doimet** [comment]
好像文字渲染出了问题，不确定再看看
你把tasklist /svc的结果粘进去，看是部分文字显示不出来还是全部文字都显示不出来，其他模块有这个问题嘛
