### ISSUE TITLE
您好，端口扫描部分需要怎么设置一下吗？还是输入有什么格式，我没弄成功

### ISSUE THREAD

**Issue by doimet** [doimet/AuxTools#7]
您好，端口扫描部分需要怎么设置一下吗？还是输入有什么格式，我没弄成功

_Originally posted by @Wangc-fly in https://github.com/doimet/AuxTools/issues/5#issuecomment-1268463727_

**Comment by doimet** [comment]
这是3.2版本因改变数据存储方式产生的BUG，3.3版本将修复
还有挂上Socks代理做端口扫描会使结果不准（这个问题还未解决）
可以挂VPN扫描😉

**Comment by Wangc-fly** [comment]
感谢师傅解惑
